INSERT INTO CIDADE_TB (NOME, ESTADO, HABITANTES, ANOS) VALUES ('paraibano','ma', 22000, 67);
INSERT INTO CIDADE_TB (NOME, ESTADO, HABITANTES, ANOS) VALUES ('colinas','ma', 65000, 127);
INSERT INTO CIDADE_TB (NOME, ESTADO, HABITANTES, ANOS) VALUES ('sjp','ma', 19000, 34);
INSERT INTO CIDADE_TB (NOME, ESTADO, HABITANTES, ANOS) VALUES ('pastos','ma', 98000, 198);
INSERT INTO CIDADE_TB (NOME, ESTADO, HABITANTES, ANOS) VALUES ('salto','sp', 322000, 200);